name = "backend"
compatibility_date = "2023-12-01"

# [vars]
# DATABASE_URL = "postgresql://akhilesh423:VxqYgdl0JNC8@ep-fancy-forest-a55eshwm.us-east-2.aws.neon.tech/neondb?sslmode=require"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"